# Generated by Django 5.0.4 on 2024-04-08 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('relationship', models.CharField(blank=True, choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Sister'), ('B', 'Brother'), ('D', 'Daughter'), ('N', 'Son')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.country'),
        ),
        migrations.AddField(
            model_name='member',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='misc.state'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Un', 'Unassigned')], max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('M', 'Member'), ('AM', 'Attende'), ('V', 'Visitor'), ('N', 'Non Longer Attends'), ('U', 'Unassigned')], max_length=2),
        ),
    ]
