# Generated by Django 5.0.4 on 2024-04-09 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_family_address_country_member_year_of_birth_and_more'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='mother_name',
        ),
        migrations.AddField(
            model_name='family',
            name='member1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_member1', to='member.member'),
        ),
        migrations.AddField(
            model_name='family',
            name='member2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_member2', to='member.member'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adddress_country', to='misc.country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adddress_state', to='misc.state'),
        ),
    ]
