# Generated by Django 5.0.4 on 2024-04-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_remove_family_father_name_remove_family_mother_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='member1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='family_member1', to='member.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='member2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='family_member2', to='member.member'),
            preserve_default=False,
        ),
    ]
