# Generated by Django 5.0.4 on 2024-04-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_family_member1_alter_family_member2'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Single'), ('W', 'Widowed'), ('D', 'Divorced'), ('Un', 'Unassigned'), ('S', 'Separated')], max_length=2),
        ),
    ]
